language: python
sudo: required
services:
- docker
env:
  global:
  - DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
matrix:
  include:
  - python: '2.7'
    env: PYVER=cp27-cp27m
  - python: '3.4'
    env: PYVER=cp34-cp34m
  - python: '3.5'
    env: PYVER=cp35-cp35m
  - python: '3.6'
    env: PYVER=cp36-cp36m
  - python: '3.7'
    env: PYVER=cp37-cp37m
install:
- pip install --upgrade setuptools  # work around https://github.com/pypa/setuptools/issues/1086
- pip install .
- pip install -r requirements.txt
- docker pull $DOCKER_IMAGE
script:
- if [[ "$PYVER" != "cp37-cp37m" ]]; then python -m nose asynq; fi  # tests don't work properly in 3.7 because we use "async" as a deprecated alias; TODO find a workaround
- if [[ "$PYVER" != "cp27-cp27m" && "$PYVER" != "cp34-cp34m" ]]; then pip install mypy; fi # mypy requires python 3.5+
- if [[ "$PYVER" != "cp27-cp27m" && "$PYVER" != "cp34-cp34m" ]]; then mypy asynq; fi
- docker run --rm -e PYVER -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh
- ls wheelhouse/
- mkdir -p dist/
- cp wheelhouse/asynq-*.whl dist/
- if [[ "$PYVER" = "cp37-cp37m" ]]; then python3.7 setup.py sdist; fi
deploy:
  provider: pypi
  user: Quora
  password:
    secure: b2A+mT8MrCQ2ON0tNrBHoXtkIyZGRNJzmxh6fibmjpD7d+H4y7jXKpABr6uxnBZkl+X4cN5izeGUs4Xdze06LKP8drJH16FSg9LeGWIW/KUHE4ecsX1WbMrjIQDeW5LtAowfsnA8y7vnyofx/MzZklunASKZGupr7LyhJhcsx7fJQ6cIXQXB4WI7nIco3FXxCVzYCcmpzhlzJdMvy8PXY+q422Au/rdJC6lw6Jy7IjMEVDYXnb7E5hfhnXGwmJkJ7I1X0fdyhhgdVSTvvjDe7Ubcvrape45L8yiDf93ftAhHl0FrQXcYtggRPYpIYEOFUbLnzHS8iO1rbbsS4CxZnd7Z9zQ7urO0xhPknqBKcxlVT976IWzdxkXm+TM9lvW4yhaNKAOvKnxHmPuhSXHNFHbD0jPGuD03qmJuiNKNsVwOtiSFnBFOzoMwQ7gKAYKPtxO4rIcP+PQiRucVJUTfLvE8m69nIaiBd32Wiwv2LLrvDFHtzgqMckXxD0bSzhildCb52T3HMcmoAK8zsnrtL8bZ2pWqbkTMqsd8F5SyugUMdObKDtkielUcEDUugJub+S5jw6U9GKz3I4LKgpZi0K3gFboM17Vf6hN8Svx7U4qEpbyzJHl91lwE+SWchaea+kwk5baI4BBkoASxgAIv5abSmpFTefe+Zxbz8yPw5pI=
  on:
    tags: true
  skip_cleanup: true
  distributions: build_py
